### PR TITLE
Fix #1. Updating the video for depsdev v0.0.6

### LINKED ISSUE #1: Update gif for depsdev README
https://github.com/edoardottt/depsdev

Update the depsdev [GIF](https://github.com/edoardottt/images/blob/main/depsdev/depsdev.gif) using the latest depsdev version.

### PR DESCRIPTION
**Pull request by carlospatinos**
Updating the depsdev.gif and adding depsdev.tape

If you like it can you merge it and also label this with hacktoberfest-accepted

Thanks

### CODE REVIEW

**Comment by edoardottt** [comment]
Thanks @carlospatinos ! Can you add the source code too please? 

In case in future I'd like to edit that

**Review by edoardottt — CHANGES_REQUESTED** [review]
maybe a little bit of pause between a command and another would be better. Also in the command typing. If you add the source too we can review the pauses better

**Comment by carlospatinos** [comment]
The source code is the .tape file, both were added to the PR. Take a look and let me know if thats ok

**Comment by carlospatinos** [comment]
Let me take a look it seems the tape is a binary instead of the source code I will fix that and the timing too

**Comment by carlospatinos** [comment]
Both tape and gif updated and a small delay added as requested

**Review by edoardottt — APPROVED** [review]
lgtm

**Comment by carlospatinos** [comment]
Thanks to you, if you need help with other things let me know pls

**Comment by carlospatinos** [comment]
Can you add the topic hacktoberfest to your repo please Thanks

**Comment by edoardottt** [comment]
> Thanks to you, if you need help with other things let me know pls

See https://github.com/edoardottt/images/issues @carlospatinos 



> Can you add the topic hacktoberfest to your repo please Thanks

Done.

**Pull request merged**
